### ISSUE TITLE
Feature request: Track/Update bower.json file

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#112]
It would be nice if CK could:
- read a `bower.json` file in the project's root directory to determine bower assets to include.
- automatically update a `bower.json` file when assets are added to the project via CK.

**Comment by bdkjones** [comment]
I've decided to close feature request issues on the beta repo. The reason is that I _have_ to get this app shipped and that means locking the feature set so I can concentrate on killing bugs. 

Once the app goes public, I'll take feature requests again and start implementing them for the 2.x releases.

**Comment by calvinjuarez** [comment]
I'd really like to see this implemented.  Since this repo isn't really the "beta repo" anymore, I think this issue should be re-opened.
