### ISSUE TITLE
CodeKit Server replaces instances of server name instances on page (Beta 6)

### ISSUE THREAD

**Issue by frank-laemmer** [bdkjones/CodeKit2#130]
this is a more minor thing: 

my project vhost is called "my-frtrabbit" in MAMP pro, when previewing via CK2 (beta 6) it changes the URL to "fuckup.local:5757". (fuckup is my computers name).

Now, when the name of vhost (project) is also part of rendered HTML it will replaced as well. i guess for most projects this doesn't will make a different.

![screen shot 2014-01-07 at 21 38 57](https://f.cloud.github.com/assets/962736/1863080/4be8194c-77dc-11e3-9f7b-79d038862983.png)

**Comment by bdkjones** [comment]
Yea. This is how the proxy server works. 

I don't actually parse the rendered HTML; I just do a string replace where all instances of the external server address are replaced with the internal one. The reason is speed: it's much faster to just replace all instances than it is to figure out if a given instance of the external address is just text on the page.

Behaves as intended.

**Comment by frank-laemmer** [comment]
Agree, it's an unlikely case anyways.
