### ISSUE TITLE
Browsers are not being updated when changing projects

### ISSUE THREAD

**Issue by johnsardine** [bdkjones/CodeKit2#135]
**What's the problem?**

Browser is not updating correctly when changing projects.

**How to reproduce?**

Download [this](http://cl.ly/TFWS) folder, called codekit, that contains 2 projects, inside. Place it inside the localhost folder.

`http://localhost/codekit/test1/` and `http://localhost/codekit/test2/`

Add both to codekit (i opened with shift pressed and added).

Click preview and change projects.

Test 1 is red, Test 2 is green.

Test this too: Preview test 1, change to test 2, edit test 2 index.html
What happens is, test 1 opens, when changing to test 2 doesn't update and when editing the index on test 2, the content updates but the assets don't (background should be green on test 2)

Im using the latest beta, in `Mavericks 10.9.1`, previewing in `Chrome 31.0.1650.57`, `Safari 7.0.1` and `Safari on iOS 7` and using `Coda`.

**Comment by bdkjones** [comment]
_Sigh_. Two steps forward, one step back. 

Thank you for the demo projects. I've been able to reproduce the problem on my end and will fix it.

**Comment by bdkjones** [comment]
Okay. The issue is browser caching. If you clear your browser cache each time you switch projects, you will see the new project loaded correctly. This issue affects only external server projects.

I have fixed this in Beta 8 by getting SUPER aggressive about nuking cache-related HTTP headers, in both the HTTP request from your browser AND the HTTP response from the origin server (Mamp, etc.) I'm now killing all of them.

Beta 8 should be out late tonight.
