### ISSUE TITLE
Update All Installed Components, bower update, doesn't work

### ISSUE THREAD

**Issue by pmeissner** [bdkjones/CodeKit2#165]
I'm trying to update my Foundation to the newly released 5.0.3 but selecting "Update All Installed Components" does nothing.

OS X 10.9.1

![screen shot 2014-01-16 at 8 53 00 am](https://f.cloud.github.com/assets/392386/1930908/160bf3e4-7eb6-11e3-8e85-bceff7a20fa0.png)

**Comment by bdkjones** [comment]
The reason this is not working is that the code has literally disappeared:

![screen shot 2014-01-17 at 19 59 29](https://f.cloud.github.com/assets/926566/1945843/ce7c8292-7fdb-11e3-909d-2847c93ec6a0.png)

I have no idea where it went. Fixed in Beta 11.

**Comment by bdkjones** [comment]
Right. I remember now. I pulled this code out back in November because Bower's update functionality is totally borked. When I put it back in, it didn't work. Again.

See this issue --> https://github.com/bower/bower/issues/1054

I'm waiting on word from the Bower team. If they don't fix it promptly, my backup plan is to make the update command in CodeKit simply remove and reinstall the components in question.

**Comment by bdkjones** [comment]
Implemented in Beta 11, but it's just a force-reinstall of already-installed components. Same result, just a rather cumbersome approach.
