### ISSUE TITLE
Can't load server on iPhone

### ISSUE THREAD

**Issue by donaldallen** [bdkjones/CodeKit2#166]
I'm trying to do some device testing but I'm not having any luck. My computer and iPhone are on the same network:

![problem01](https://f.cloud.github.com/assets/453784/1941737/0744f976-7f8f-11e3-8873-96c104a23dad.png)

And here's what the browsers look like on both Mac and iPhone:

![problem02](https://f.cloud.github.com/assets/453784/1941746/1f4fac00-7f8f-11e3-94f7-c9a9a1987486.png)

Going to the same address on both. On the iPhone, it just sits and tries to load for about a minute, then gives up (with no error). I've also tried going to the IP address, and that's an instantaneous "not found".

So same WiFi network, same Subnet Mask/Router/DNS, but nadda.

Weird thing is, this actually works just fine in iOS Simulator. If I have that open, and save anything I'm working on, it gets refreshed like any other browser would.

Not sure if this is a CodeKit issue or a "I suck at networking" issue, but I would like to be able to test this feature.

**Comment by bdkjones** [comment]
The first thing to try is a different Wifi network. It's highly likely something is misconfigured.

**Comment by bdkjones** [comment]
The short answer is that I have no idea what's going on. You're the first person to ever report this.

Can you access your computer via its local IP address or Bonjour name across the LAN outside of CodeKit? For example, when you use another Mac connected to your network and open the Finder, do you see your original Mac listed under the "Devices" section? Can you SSH into your Mac across the LAN?

The iPhone simulator works fine because it uses the same IP address as your Mac. It communicates over the local feedback address (127.0.0.1). It sounds to me like your router is blocking communication across the LAN. I'd start by looking there.

**Comment by DDDgfx** [comment]
I am having this problem as well. Using a Netgear WNDRMACv2, which also I have been noticing causes trouble with home sharing in iTunes. Sometimes a router reboot helps, but home sharing, file sharing and also the iPhone app RemoteMouse all demonstrate inconsistent behavior on this network. I am curious about what setting I need to change or unchanged to improve the issue.

**Comment by bdkjones** [comment]
Are the problems appearing only on this network? If so, the router is the likely cause. How old is that router?

**Comment by DDDgfx** [comment]
The router is less than a year old with the firmware updated. BI am convinced that its the router though. But I also still believe there is some setting in the firewall or something I can change to fix.. There are clear issues mac/IOS networking on it. 

For example, if I create a wifi network using the machine running codekit, and then connect to it with the iPhone.The pages load.
- D

On May 5, 2015, at 4:02 PM, Bryan Jones notifications@github.com wrote:

Are the problems appearing only on this network? If so, the router is the likely cause. How old is that router?
