### ISSUE TITLE
Small UI issue: Projects 'window' and scrolling

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#182]
When the project 'window' / dialog is open and the mouse wheel is used, a small scrollbar becomes visible (like in all other OSX apps). This scrollbar does not overlay the checkboxes of the projects (yet ;).
However, if I put the mouse cursor close to the right edge of the window, the scroll bar resizes (doubles in width[?] - as almost all apps do), but this time the scrollbar almost covers / overlays the checkboxes.

Not as much as in Codekit 1 but still a bit. Maybe moving the checkboxes a little bit to the left would help? I know this is a problem of the OS.. 

Quick screencast demo of what I tried to describe: http://dl.dropboxusercontent.com/u/81358/jing/codekit-scroll.mp4

![screen shot 2014-01-21 at 24 09 18 am](https://f.cloud.github.com/assets/3019226/1959183/f56bc338-8227-11e3-8969-9d509be44904.png)

**Comment by bdkjones** [comment]
Yep. Every app on OS X faces this problem because of the way the system scrollbars operate. I'm not going to move the checkboxes to the left, because then 98% of the time they would look weird and only 2% of the time would they be appropriately positioned.

Right now, 98% of the time, they are in the perfect spot. Apple needs to fix this in OS X.
