### ISSUE TITLE
Problem with Susy and frameworks

### ISSUE THREAD

**Issue by bakura10** [bdkjones/CodeKit2#183]
Hi,

I'm using Susy for grids. Susy 2 is currently in beta so I wanted to try it. I added it as a new framework called "Susy 2" next to "Susy 1", so I still can compile my old projects with CodeKit (that's why I don't use CodeKit built-in frameworks, because of the issue of BC between versions).

Then, in the project settings, I unchecked "Susy 1" so only "Susy 2" is left. I refreshed the project, and I expect that @import "susy" would load the susy file from "Susy 2" code kit framework. However it still loads the one from Susy 1.

Actually, I'm not sure if this is a problem with the framework checking OR if CodeKit decide to use the built-in Susy instead of my one. I'd say that if a file is in a framework, it should absolutely override the built-in ones in CodeKit.

Thanks!

**Comment by bdkjones** [comment]
Should be fixed in Beta 13. CodeKit will now look for "susy.scss" in your CodeKit frameworks before it falls back to the version of Susy that ships with the app.

NOTE: in 2.0, you must specify the full path to a framework file, relative to the root framework folder. So, if susy.scss is here:

```
/Users/you/desktop/myframework/subfolder/susy.scss
```

And you have added "myframework" as a CodeKit framework, your @import statement would need to be:

```
@import "subfolder/susy.scss";
```

Otherwise, that file won't be found.
