### ISSUE TITLE
Adding and refreshing a project can take up to 10 minutes

### ISSUE THREAD

**Issue by C-Benz** [bdkjones/CodeKit2#192]
Starting Codekit (2 active projects) for the first time always takes about 10 minutes. Refreshing a project can take close to that as well. Compiling SCSS with libsass takes about 7 or 8 seconds which is a lot longer than I would have expected.

I'm running OS X 10.9.1 and Coda 2.0.12. 

Web files are on local network Mac Mini running OS X 10.9.1 with Server app that handles DNS. This server is running the latest Mamp Pro with vhost set up for each project. Browser refreshing works most of the time so I believe the project is configured properly.

I read that if both networked computers are running Mavericks they use the SMB2 file sharing protocol and there are issues with this implementation. Maybe an issue?

**Comment by C-Benz** [comment]
Looks like the issue was because of a massive number of files in the project. I was able to limit those by adding rules to the skipped items field and this sped up codekit immensely.

One super helpful tweak to this would be to allow me to specify the files and directories I WOULD like codekit to watch in addition to the files I WOULD NOT like to watch. I really only ever need codekit to watch 2 directories in any of my CakePHP projects. This would prevent me from having to tell it to skip every other possible directory which is a pretty extensive list.

**Comment by bdkjones** [comment]
Yea, if you're working over a network you should expect slowdowns.

There's nothing I can do here; the limiting factor is the speed of your network. Using 802.11ac will help, but that's still on the horizon and all your devices would need to be updated to be compatible. The simple truth is that working over any network is going to be slower than working locally on your Mac. If you're using a network, you need to be very careful to skip unnecessary files and folders. 

As for opting-in to folder watching instead of opting-out: it adds another step to the process of adding a project to the app. I'd have to pop up some sort of window that says, "Now, which things did you want to watch?" which would be annoying and wasteful for the vast majority of users.

**Comment by bdkjones** [comment]
As a test, copy the Sass file that's taking 7-8 seconds to compile and put it on your local hard disk (along with any imported files). Compile it from that location. I'll bet you find that's it's massively faster, indicating that the bottleneck is the file read/write operations that go out over your network.
