### ISSUE TITLE
Cannot set custom image

### ISSUE THREAD

**Issue by bakura10** [bdkjones/CodeKit2#20]
Hi,

Not really a bug, but I'd like if we could set custom image for projects (if it's already possible, I couldn't find the option). If this option could be made available for frameworks too it could be awesome. I'd like to use this to add the logo of each project as well as the logo of the library I add as framework.

Thanks !

**Comment by marpala** [comment]
+1. This would be fantastic.

**Comment by mdavis1982** [comment]
:+1: for this feature, too

**Comment by guill3m** [comment]
:+1: +1

[MacRabbit's Espresso](http://macrabbit.com/espresso/) has a really nice way to do this while keeping visual consistency with the application: it uses a transparent png for the project logo, that way it shows the opaque parts of the image and hides the transparent ones so you get a one-color logo/symbol for the project, as well as the color you choose for it.

**Comment by yratof** [comment]
If the project has a favicon, could It pull from that?

**Comment by kennonb** [comment]
+1

I think the favicon is a great idea as well.

**Comment by guill3m** [comment]
The favicon seems really small for the size of the project image to me, it would be great for the sidebar, but I doubt it would look nice for the project image.

**Comment by kennonb** [comment]
While true, most sites have to have an iOS optimized graphic, so it could use the 144x144 "touch" version instead. Granted that probably wouldn't be sufficient for retina screens, but it could work as a stop gap.

**Comment by yratof** [comment]
Perhaps; You could use windows 8 tile images which are much larger than the ios icons, but then CK2 is looking for too many icons, I was imagining the 32x32px favicon would be easier to pick as it's standard. I guess it's just easier to differentiate between projects if icons are your thing. The retina issue for me doesn't really matter, since the rest of the internet has the same icons

**Comment by rpkoller** [comment]
+1

**Comment by bdkjones** [comment]
Yea. This is exactly why we nixed custom images: it's very easy for them to look like crap. 

We do have some plans here down the road, and each 2.x update will bring more icons to choose from. For now, this is on hold.

**Comment by edwardsdesign** [comment]
I think this feature would be very helpful for people / groups that are working with multiple clients. In this scenario a company's logo could be used as the custom icon, easily allowing a user to switch between projects at a glance rather than having to read. That is the point of the icon right, visual recognition?

My main concern is that the icons right now are very well done, I am particularly fond of _overly attached girlfriend_ however, they are limited. There are only so many combinations of colors and glyphs that can be created and still make some sense as to which project is for what client. Yes a custom image might look like crap for those who do not take the time to create one that looks good with the dimension you have specified however for the ones that do, I feel it would give a very nice polish to all of those screen shots showing off the new and shiny CK2.

Did I mention the polish and screen shots showing off the new CK2?

Just my .02¢

**Comment by mkoistinen** [comment]
I gotta say, this is a must have feature! My mind already has an icon embedded in it for every project, and its the one I make at the start of a project specifically so I can keep my projects organized in my browser tabs.  I've even been known to make different versions for local vs. remote production servers, so that I can keep them straight even then (they look very similar, my local dev ones just have a dog-eared corner effect).

Anyway, If you're focused on making this automatic, scanning for 'touchicon', 'tileicon' or 'favicon' should be a piece of cake, then just select the one with the largest dimensions. In fact, if you look for PSD files too, you may find that some devs (like myself), make these images at 512px square, then scale down as required for the various versions, so, you could get a lot of pixels to work with.

Even if you don't auto-select one, let the dev drop the icon of their choice in, with a "protip" tooltip that says to use one of at least XXX square for Retina goodness.

Having said all of this, I don't think its a coincidence that you're starting with 144px square images, I suspect you planned on doing something with this all along ;)

**Comment by mgrn0** [comment]
+1

**Comment by sethta** [comment]
Thanks Brian! I've updated the icons on all of my projects and it looks great.

**Comment by mkoistinen** [comment]
AWESOME! Thank you, Bryan!

**Comment by lucien144** [comment]
:+1:
