### ISSUE TITLE
Output paths not updated when duplicating and renaming a folder...

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#209]
When teaching, sometimes I create one codekit project with subfolders for demos and exercices.

Each subfolder is a kind of "mini-project" with its own dev/css folders.
If I copy/paste a subfolder, output paths are correctly updated.
But when I rename the subfolder, CK keeps the "subfolder - copy" path...
And when I compile, the temporary "subfolder - copy" is recreated with the temporary output path.

![capture decran 2014-01-30 a 23 22 35](https://f.cloud.github.com/assets/806883/2045732/180dbfc2-89fd-11e3-8827-07d92e581a35.png)

I know this is a very specific use case but maybe it can happen in more real   situations...

**Comment by bdkjones** [comment]
Yea, by default CodeKit will not alter your output paths if you rename a folder. It's a tossup because half the people will want it to automatically change the output path and the other half will scream bloody murder when they can't figure out why their output file is no longer updating. They will waste lots of time trying to debug it, then fire off an angry email to me and only then realize that their output file magically changed locations (because of course they don't remember renaming something, which triggered that). So the new output was in a different location all along and they were looking at the old output file. 

You see where I'm going with this? I choose safe behaviors whenever possible.
