### ISSUE TITLE
config.codekit `files` structure reordered on unrelated change causing misleading diffs

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#222]
Even though I change something unrelated the `files` entries in the `config.codekit` file are sometimes reordered following some rules unknown to me. As I keep this file in the git repository that means that every time a misleading change set is created and it's hard to keep track of the real changes in the file.

To reproduce change for example `Uglify.js` settings (e.g., toggle `screw-ie8`) and observe the order. Toggling the `screw-ie8` checkbox won't roll back the order change. Or maybe sometimes. "Though this be madness, yet there is method in it" because sometimes the entries seem to be changed back to the original order. No idea what the logic is. 

Tried recreating everything (quit, remove `config.codekit`, relaunch with Shift key) but it didn't help.

(You may say that I could exclude the config file from git but it contains important information on file imports and other settings so I would like to have it there.)

**Comment by bdkjones** [comment]
The answer is that the config file is a JSON file and JSON does not order key-value pairs. CodeKit's internal data model is unordered because it's much faster than trying to keep everything sorted.

However, I've implemented a custom JSON parser that will maintain alphabetical order in the config file. I've been able to find a way to do that performantly. Fixed for Beta 15.

**Comment by zengabor** [comment]
I am very grateful for that. Thank you!
