### ISSUE TITLE
Concatenate js files without minify and or sourcemap generation leave codekit-prepend in output file (Beta 14)

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#225]
i have the following settings: 

![bildschirmfoto 2014-02-01 um 23 57 08](https://f.cloud.github.com/assets/1665422/2059072/31a395a8-8b95-11e3-8455-38bdac7b4969.png)

the head of one of my js files looks like that: 

![bildschirmfoto 2014-02-02 um 00 05 50](https://f.cloud.github.com/assets/1665422/2059085/b0f11196-8b95-11e3-9251-559e576f5627.png)

if the files get processed with the settings from the first screenshot the result looks like that. 

![bildschirmfoto 2014-02-02 um 00 07 11](https://f.cloud.github.com/assets/1665422/2059087/ccbe4f88-8b95-11e3-84f7-189dbf57b59b.png)

would have expected that the //@codekit-prepend (same with @codekit-append) parts would have been stripped out.  if i search in the minified version i am unable to find codekit-prepend. there it seems to be processed as expected.

**Comment by Andreyco** [comment]
I think, minified files is processed with another tool, which strips comments out.

**Comment by bdkjones** [comment]
Yep. The answer is that it's faster to simply throw all the files together than it is to parse line-by-line looking for @codekit-append/prepend statements. 

I could do that, but it would just add to the time it takes to combine all the files together. (Obviously, it's a very tiny amount of time, but I'm really loathe to do anything that slows down CodeKit --- the app has a huge advantage over other tools out there that rely on Node.js because it uses C, which is orders of magnitude faster than Javascript. I get a lot of email from folks that have switched from other tools and are surprised at how fast CodeKit is. I do everything I can to keep that speed maximized.)
