### ISSUE TITLE
The change of the Bower components folder if the bower_components already exists should lead to a folder move or at least an alert

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#226]
situation at the moment (beta 14):
- create a new project
- leave the bower_components folder setting on default for the moment. 
- download a bower component ( one of the favorites e.g.) 
- then go to the general project settings and enter a new location aside the default root folder for the bower_components folder (e.g. js/bower_components). 
- now download another bower component. 
- you will have two bower_components folders. one in the root and one inside the js folder

i would suggest that the bower_components folders would get moved from the old to the new location by codekit to prevent 2 or more bower_components folders within the project folder or at least some alert panel telling that the user already downloaded one or more components and that there actually already is a bower_components folder and if it should be moved for the user or if he or she wanna proceed manually. But without any notice the present state holds the opportunity of trouble sooner or later imho.

**Comment by bdkjones** [comment]
The current approach is meant for safety. 

If you move the bower_components folder, then you would need to go update all the href attributes in various pages that pointed to the old location. This is why CodeKit does not relocate the folder automatically --- it makes you do that manually so that stuff does not break.

The current approach also allows you to have more than one bower_components folder. Why you would do that is beyond me, but then again, so are many of the workflows my users tell me about.

In general, CodeKit never tries to "guess" your intentions.

**Comment by rpkoller** [comment]
@bdkjones  ok the safety reason i completely understand. but then i would still go with an alert panel on bower_components location change. add maybe also a checkbox with "don't show again the next time" - that this thing don't gets too nagging. but in general inform the user that the location is changed and that he or she has to move the folder from the old to the new location including updating the hrefs in the case they don't want to have another bower_components folder inside their project folder. cuz me for myself e.g. am uncertain if an app doesn't do anything that i might break something if i just move the folder on my own, in fear that there is still somewhere a hidden bower settings file, dependencies and whatever that might cause issues if i move things on my own.  there for i would still vote for some sort of educational alert panel.
