### ISSUE TITLE
Settings groups open/collapsed

### ISSUE THREAD

**Issue by C-Benz** [bdkjones/CodeKit2#234]
This is super minor but I'm wondering what the logic is behind which settings groups are open on the project settings sidebar. I usually only ever drill down on "Languages" but "Syntax Checkers" is always open for me when I start up CK. I doesn't really bother me - just curious if there is a reason that one is always open. It would be sweet if CK remembered which groups were open/collapsed. Thx!

![screen shot 2014-02-05 at 1 47 51 pm](https://f.cloud.github.com/assets/4439110/2092066/5b57cd8c-8ea7-11e3-9bfe-95f5c888d909.png)

**Comment by rpkoller** [comment]
hmmm in beta 15 the open and collapsed states are remembered. at least over here.

**Comment by C-Benz** [comment]
Chiggity check it......

https://www.dropbox.com/s/zt7yhm6ervi8prg/codekit_project_settings.mov

**Comment by bdkjones** [comment]
The app remembers the open/collapsed state while it's running. On each relaunch, it starts from the default state.

The answer here is very simple: if you make the CodeKit window as short as possible, then expand all the options in that list, the bottom gets cut off. Therefore, Languages is always collapsed by default so that first-time users will see "Hooks" and "Minifiers" when the window is small.

**Comment by C-Benz** [comment]
Cool - makes sense
