### ISSUE TITLE
Todo directly in the code 

### ISSUE THREAD

**Issue by jonnitto** [bdkjones/CodeKit2#246]
I saw a feature in Hammer for Mac: Todos. It would be great if there where a possibility to write todos directly in the code, and Codekit would display it right in the interface.

**Comment by kmmathis** [comment]
Todos are cool, but I personally feel that they are best left at the text editor or project management software level, rather than being tacked on to CodeKit. CodeKit is really great at what it does, and I'd rather see it stay focused on that rather than add on extra features. Just my humble opinion.

**Comment by mgrn0** [comment]
+1 for kmmathis, I am sure Codekit is used with LOADS of differend IDEs and each has its own system for todos (or not). I would not like to have another set of todos spread across files..

**Comment by bdkjones** [comment]
I've thought about this in the past, but you don't edit code in CodeKit, so what's the use of todo's in the app? That said, I have considered a "project summary" screen that would potentially show them. I'm not ruling the idea out completely, but it's a bit low on the priority list. 

Right now, I'm closing feature requests so that I can actually ship 2.0.
