### ISSUE TITLE
Automaticaly include reset.css and normalize.css

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#248]
Hi there.
I don't have to mention that CK2 super awesome and I like Nib support but I would like to see CK2 automaticaly include `reset.css` or `normalize.css` if specified in `@import` statement.

Is that possible? Does someone find this good idea?

**Comment by maxlapides** [comment]
This seems like a good use for CodeKit frameworks.

**Comment by bdkjones** [comment]
Agree with @maxlapides. Just because you use those items doesn't mean that everyone does. CodeKit is a tool that needs to be flexible for thousands and thousands of people. If I started automatically including stuff in your files, 50% of users would be happy and 50% would curse me. So, I give you the flexibility to set it up yourself, customized for your own workflow.

**Comment by rpkoller** [comment]
i agree too. and @Andreyco if you are using compass `@import` 'compass/reset'; already does the trick and provides you with the css reset. and with bower the normalize part is also easily to accomplish. download the normalize version you desire via bower and link it directly with `@import`
