### ISSUE TITLE
Server path question

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#251]
Probably not an issue, but just in case...  I have a site folder structure like so:

![screen shot 2014-02-12 at 4 25 41 pm](https://f.cloud.github.com/assets/835148/2153816/8d065a58-942c-11e3-8773-fb29c068df8a.png)

I have MAMP pointed to the top folder "design-system" as the site root. Everything works in MAMP directly. 

To get everything to preview correctly in Codekit, I needed to use the external server and set the subdirectory to the one with my index.html, as so:

![screen shot 2014-02-12 at 4 29 35 pm](https://f.cloud.github.com/assets/835148/2153841/cf29c4ba-942c-11e3-83c0-d214a3fb33e3.png)

This is as designed, correct?  It seems to work fine. I'm glad the app is so flexible.

**Comment by bdkjones** [comment]
Yep, this looks good. But bear in mind that if you have any root-relative paths in your code (URLs that begin with a `/`), those paths are going to be resolved from the External Server Address, without accounting for the "Preview Subpath".

Example: if `index.html` has this code:

```
<a href='/blank.html'>link</a>
```

Then when you click that link, CodeKit is going to request this path from your External Server:

```
http://design-system/blank.html
```

Which will fail, because blank.html is in a subfolder. In short, YOU are responsible for making sure root-relative links match correctly with the folder you set as the document root for your external server.

In the example above, you would need to edit the line to be: 

```
<a href='/docs/assets/blank.html'>link</a>
```

**Comment by JMarqz** [comment]
What about the files included in my head HTML like this `<link rel="stylesheet" href="../style.css">`?

All that files are not finding. I very new in CodeKit, I missing something?

I get my structure like this:
<img width="288" alt="ck-structure" src="https://cloud.githubusercontent.com/assets/6549789/8609249/718a0372-2668-11e5-97f5-ded72bf3c9b5.png">

And my browser refreshing settings are:
<img width="575" alt="ck-root" src="https://cloud.githubusercontent.com/assets/6549789/8609289/ff8eec64-2668-11e5-9f63-f591c54a82f9.png">

**Comment by bdkjones** [comment]
You’ve set a document root at “html”. CodeKit won’t go above your document root to resolve relative links—that’s what a document root is for. 

Your project structure is not valid. Put your index.html in the _ACTUAL_ document root, which is your project folder. Or, put all the other content for your site under the document root folder you specify in Project Settings.

**Comment by JMarqz** [comment]
Thanks a lot for clarify me. Make sense! Thanks a lot!
