### ISSUE TITLE
Removing Components

### ISSUE THREAD

**Issue by jayfreestone** [bdkjones/CodeKit2#26]
In order to remove components you have to delete the files and then hit 'Determine installed components'.

I think a remove button should either be there or hitting the refresh button should do this already. Took me a while to figure out how to tell Codekit a component has been deleted.

![screen shot 2013-12-18 at 14 44 21](https://f.cloud.github.com/assets/3719745/1774022/eab151b4-67f2-11e3-853b-3022fcef6372.png)

**Comment by mdavis1982** [comment]
I don't think this is a bug, but more of a "clarify and refine how this works" request.

@bdkjones I'm :+1: of tweaking this.

**Comment by jayfreestone** [comment]
Along those lines, any way to install components not in the root of the project (e.g. in the WordPress theme directory, not in the root of the WordPress install)?

I'd make the theme the project root but it breaks asset URLs for the preview.

**Comment by mdavis1982** [comment]
@jayfreestone I don't think there is. Can you open a separate issue for that please requesting that there is a project-level option for the output path for bower components? Thanks!

**Comment by bdkjones** [comment]
The issue is that CodeKit has to run a full Bower command to determine exactly what components are still installed. Bower is _super_ slow, so running that command repeatedly is annoying. The app currently re-checks for installed components each time you open the Assets area. 

Bower is designed by a bunch of guys that love the command line. It is not, in any way, very API friendly for a graphical app.

**Comment by mdavis1982** [comment]
@bdkjones Would it be possible to only run that command when you click the "remove" button? I know from experience that Bower is super slow - maybe we could get a visual spinner or something displaying whilst it's running?

**Comment by bdkjones** [comment]
Bower's remove command is functionally freaking retarded. That's why I haven't implemented it. 

If you have jQuery and jQuery UI installed in your project and you go to remove jQuery UI, bower will automatically remove jQuery as well because it looks at your installed components and says: "Oh, nothing else is using jQuery so it must not be needed." In reality though, you likely WANT to keep jQuery around because your HTML files and other stuff use it. All Bower is aware of are other components you've installed. If no other components use something, Bower nukes it. 

The entire Bower project is built by a bunch of command line junkies that build "apps" in Javascript. Bower is designed for that type of project, not for building Websites. Having it in CodeKit at all took a lot of hacking.

**Comment by bdkjones** [comment]
I've decided to close feature request issues on the beta repo. The reason is that I _have_ to get this app shipped and that means locking the feature set so I can concentrate on killing bugs. 

Once the app goes public, I'll take feature requests again and start implementing them for the 2.x releases.
