### ISSUE TITLE
Compiling option for :quiet possible?

### ISSUE THREAD

**Issue by geebru** [bdkjones/CodeKit2#263]
SCSS will print errors for deprecated techniques, as it should, but in Bourbon, one of the files uses a "soon-to-be" deprecated global variable technique.

This is more on Bourbon, but it did raise the thought of allowing users to use the :quiet option or any other SCSS command line options from the GUI. Just putting it out there for discussion!

**Comment by bdkjones** [comment]
You can pretty much make this happen by un-checking the "bring to front" and "beep" options in the Preferences window.

The trouble is that I don't want to allow :quiet because the stuff that the compiler warns you about is actually pretty important and folks will just turn on quiet and then keep it on permanently, which means they'll miss future deprecation warnings and things they should be aware of.

**Comment by geebru** [comment]
Very valid point!

Thanks for your work on this, I'm super pumped for the day I can share this with everyone :)
