### ISSUE TITLE
Mixing projects in log

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit2#270]
Not sure if this was reported, but I don't see this in the open issues.

It is very strange to use CK2 with multiple projects at the same time, which I am often forced to do. The log window will happily report progress/warnings/errors for the last file saved, even if it is now the one selected in the upper right of the CK interface.

I think it would probably feel more natural to the user if, when a project file is processed from a different project, that CK automatically switches context to that project, keeping the log separate for each project.

**Comment by bdkjones** [comment]
The trouble here is that automatically switching projects would also automatically change what you're previewing in your browser.

If your active project is X and you also have projects Y and Z in CodeKit, when a file in project Y changes, the app compiles it and shows the result in the log. If I implemented the proposal, your browser on every device would switch to show project Y instead of X, which may not be what you want. 

It's possible for a file to change in the background, without your explicit interaction. For example, an editor auto-save, a sync from Dropbox, the file is on a shared disk and was changed by another user, OS X updated some aspect of the file, etc.

It would appear to the user that CodeKit randomly flashed to a different project for no rhyme or reason. The log entry _does_ list the name of the project involved. I could add the ability to click that name and have the app automatically switch to the active project. 

Please file the latter as a feature request once CodeKit 2 goes live. I'll get it in for 2.1.
