### ISSUE TITLE
Saving file while refreshing project doesn't compile

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#28]
When a project is auto refreshing, when I'm saving a .scss file that includes bourbon, CK2 doesn't compile once refreshed.

After that, the project refreshes when you save, rather than compiling:

![screen shot 2013-12-18 at 16 21 49](https://f.cloud.github.com/assets/1001935/1774957/8d0ae4fe-6800-11e3-92b4-d5395ed92117.png)

THEN the text overlaps on the log:

![screen shot 2013-12-18 at 16 18 04](https://f.cloud.github.com/assets/1001935/1774924/18c87714-6800-11e3-8fac-4a0373b554d6.png)

Only for the latest compile though, not all of them:

![screen shot 2013-12-18 at 16 19 42](https://f.cloud.github.com/assets/1001935/1774934/3b264b4c-6800-11e3-9247-a3997231e78a.png)

**Comment by yratof** [comment]
Here's a screencast of my project throwing some depreciation errors and overlapping text and only refreshing a project when I save, rather than compiling.

http://cl.ly/T0Re

**Comment by bdkjones** [comment]
What editor are you saving the file in?

**Comment by yratof** [comment]
Coda 2, latest build

**Comment by bdkjones** [comment]
You know, I had counted on the fact that CodeKit 2's refreshes are so bloody fast, they would only take a couple seconds max and it would be unlikely that anyone would save a file at the same time.

Still, I suppose I should deal with this edge case.

**Comment by bdkjones** [comment]
I went back and looked. CodeKit automatically queues the compile and runs it when the app-refresh ends. You should be seeing the file compile once the refresh is over.

It's not possible to compile files while the app is refreshing its data file because compiling requires reading all the options associated with the given file. Those options may be in flux during an app-refresh (a new config file may be applied, etc.) This is why compiles wait until the app-refresh is over.
