### ISSUE TITLE
Wordpress Loads Slowly (Beta 19)

### ISSUE THREAD

**Issue by noelforte** [bdkjones/CodeKit2#280]
Hi-

I've been on this repo for a few weeks, but am only now getting started with Codekit 2. I've noticed that WordPress sites are taking a while to load, usually about 10-30 seconds after hitting the preview button.

I have MAMP fired up and set to port 80, as well as have the appropriate address set in CK project settings.

Also, I want to be sure that I'm using WordPress correctly. It's just the theme folder that we add to codekit, correct? Even though we're running everything on CodeKits server? Is there a more efficient way to run WordPress on CK2?

Thanks,

Noel

**Comment by bdkjones** [comment]
Do you have a trailing slash at the end of you external server address in CodeKit?

If not, add it. If yes, remove it.

**Comment by noelforte** [comment]
Nope...didn't have any effect.

**Comment by bdkjones** [comment]
Then I need a demo project posted for download here along with a MySQL dump of the database so I can recreate it over here.

**Comment by noelforte** [comment]
Would you like the entire WordPress install or just the theme?

**Comment by bdkjones** [comment]
Everything.

**Comment by noelforte** [comment]
K, here's the link: https://app.box.com/s/7modr1f7iyr2xof6vln9

I've included a small readme in the folder detailing the project in question.

**Comment by Veraxus** [comment]
thenoelforte: out of curiosity, have you ruled out MAMP as the culprit?

There is a quirk in MAMP (particularly MAMP Pro) that causes extremely slow domain resolution. If you have any vhosts setup, this is pretty much guaranteed to be the case.

The short solution is to edit your hosts file and make sure that all your local domains are one line, after 127.0.0.1 - by default, MAMP places everything on separate lines, and this causes OSX's domain resolution to grind to a halt.

Try this...
1. Open Terminal.app and type "sudo nano /private/etc/hosts"
2. Every MAMP item you see should be placed on one line after 127.0.0.1 (MAMP places them all on separate lines by default - this is what can cause the really slow resolution).
3. Save and close the hosts file.
4. Restart all MAMP services.

If everything runs super fast, your problem is solved. If not, try restarting your computer and check one more time.

I had almost exactly this same issue, and this was the problem for me. Every time you add a new vhost, you will need to manually "fix" your vhost by placing the new vhost domain on the same line with the others.

**Comment by noelforte** [comment]
I don't run MAMP Pro, so there aren't any vhosts in play.

**Comment by noelforte** [comment]
I'm going to mark this as closed, as I tried @Veraxus's idea about putting my hosts all on one line, and that seemed to speed things up a little. Regardless, it's not a huge problem, so consider this issue resolved.

**Comment by bdkjones** [comment]
Well, it ought to be pretty damn fast. The expected outcome is for CodeKit's proxy server to be virtually indistinguishable from going to your external server directly. It's always going to be just a _hair_ slower, but you should not really _feel_ the difference.

Is that where you're at now?

**Comment by noelforte** [comment]
It's just that I think what the general consensus seems to be is MAMP can be the hang up on working with the external server options in CodeKit, so its not really CodeKit's issue more than it is MAMP's. This isn't the first time MAMP has been slow now that I think of it, even before CK2.
