### ISSUE TITLE
Crash when installing Foundation without custom Compass installed

### ISSUE THREAD

**Issue by Veraxus** [bdkjones/CodeKit2#300]
If you use CodeKit to install the Compass version of Foundation, and have the "Use the Compass executable at this path..." option selected in CodeKit preferences... but (for some reason) don't actually have Compass installed... CodeKit crashes.

Yeah, it's a pretty dumb scenario.

**Comment by bdkjones** [comment]
Not surprising. 

I don't know how you even got the app into that situation, because it won't let you switch to an external Compass path unless it can run Compass from that path and Compass responds. Pretty much the only way to do this is to hack the plist for the app to manually enter the path for the external Compass compiler. (Or, conceivably, to uninstall Compass after switching CodeKit to use it.)
