### ISSUE TITLE
Request: Is there a way to get sass globbing to work with codekit2?

### ISSUE THREAD

**Issue by ChristiaanKZ** [bdkjones/CodeKit2#322]
Is there already support for sass globbing in Codekit2? and  if not is there any planning?

**Comment by bdkjones** [comment]
Sass globbing has been rejected by the Sass and Compass teams. It's never going to be officially supported in the language and it's really bad practice. 

I already get a TON of "my code isn't working; fix it" emails. And I waste my time going through them only to find that someone forgot a semicolon or mistyped a class name, etc. 

The LAST thing I need is to start debugging cascade issues caused by globbing.

**Comment by ChristiaanKZ** [comment]
Sorry for just ask’n

Met vriendelijke groet,
Chris Klein Zessink

Upstairsdesign
Sumatralaan 49
7314 JN Apeldoorn

http://www.upstairsdesign.nl
tel: +31 (0)6 150 107 03

**Comment by bdkjones** [comment]
Oh, no worries. Didn't mean to jump all over you for it.

**Comment by bdkjones** [comment]
I've had a change of heart on this issue. Sass-globbing will be supported automatically starting with the 2.1.1 release.
