### ISSUE TITLE
Bug: Cannot install Threejs with bower

### ISSUE THREAD

**Issue by filipecunha** [bdkjones/CodeKit2#325]
When I try to install Threejs component I get the error:
Bower failed to install 'threejs'. It returned this error information:

Code: ECMDERR
Message: Failed to execute "git clone git://github.com/mrdoob/three.js.git -b master --progress .", exit code of #128 

Then I run "git clone git://github.com/mrdoob/three.js.git -b master --progress" in terminal and it works fine.

This is codekit or bower problem?

Even if I download Threejs, put in my project and put it into the html file with script tag the page don't load in preview but works fine in localhost. Maybe I should report this it's in another ticket

**Comment by bdkjones** [comment]
As of CodeKit 2.1.5, I was able to install threejs successfully from the Assets area. 

It did take a surprisingly long time. Almost two full minutes. I'm not sure why that's the case, but it seems to have to do with Bower rather than CodeKit, as other, much larger assets install much quicker. 

I think this issue was resolved with the updated version of Bower that went into CodeKit in one of the last couple of releases.
