### ISSUE TITLE
request: HTML minifier

### ISSUE THREAD

**Issue by albell** [bdkjones/CodeKit2#328]
Hey Bryan, your position, I understand, is that all current minifiers break on edge cases. Can you show me some examples? I'm been using kangax's minifier and every time I encounter a bug, I file it, and it's fixed within 24 hours. Kangax is using Resig's HTML parser written in JS, which does gracefully handle basic nesting errors, etc.

The big wrinkle is that markup has to be valid, which is a big pain point, as it seems there's not a lot of interest/activity around the concept of HTML validation these days. A quick glance at current validators show very little current development. Most of these projects seem to have been abandoned three or four years ago. Html linting is way behind JS linting. 

That's too bad, because besides being essential for minification, validity checking sometimes does genuinely catch an error.  <a href="http://validator.w3.org/docs/devel.html">The w3C validator can be installed locally</a>. There should be a way to turn down the fussiness, and create some reasonable defaults that create less noise in the logs.

**Comment by bdkjones** [comment]
The main issue is that HTML is a language that actually _allows_ syntax errors. 

I get rude emails every day from people that think CodeKit is broken because X, Y or Z isn't working. And invariably, it's because they screwed something up. Here's the latest example:

```
<script type='text/javascript' src='some/path/file.js'</script>
```

Do you see the problem? The guy who filed this didn't. He was just mad that CodeKit's auto-refresh wasn't working. And of course it wasn't working: the damn DOM is completely invalid thanks to the error above.

So the issue for me is that the majority of people immediately and automatically jump to the conclusion that CodeKit is broken the minute their website doesn't work correctly. And introducing an HTML minifier that does not handle syntax errors (which are INCREDIBLY common in HTML) would increase my workload exponentially. People don't take the time to debug their problems; they just assume I'm at fault and fire off lengthy emails telling me to fix my app. 

For this reason, until HTML minifiers have matured to the point where they are reliable and capable of dealing with EVERY edge case (like modern HTML5 browsers, for example), I don't want to support them. I just don't have the time to deal with all the emails. 

Finally, minifying HTML doesn't really save _that_ much space. It's far better to reduce the number of HTTP requests than it is to trim a few kilobytes off of an HTML file.

**Comment by albell** [comment]
I totally hear you about wanting to steer around the Valley of the Trolls. So sorry you're the brunt of it. I imagine every author of an editor puts up with a certain amount of ranty rant. (Though in fairness, I'm sure I sent a stupid email like this once upon a time.) Can you get an intern? :)

I also agree it's not the biggest performance concern. But I regularly publish large tables that get a fairly big (33%) reduction from minification.

FWIW the "error" concept needs to be somewhat qualified. E.g. <a href="http://www.w3.org/TR/html-markup/li.html">some closing tags are now optional</a>. This is an error in XML, but not in HTML5:

```
<ul>
    <li>You
    <li>Yer Cousin
    <li>Yer Uncle
</ul>
```

The parsing algorithm Hickson wrote that is used in all modern browsers doesn't make invalid markup valid, it just falls back to a well-defined interpretation that hopefully won't break the page. Errors are still errors, and best avoided.

The guy who wrote you with the unclosed script tag in your example might have caught his own mistake had he used a validator. And you could shame him with not having listened to your built-in validator! I agree minification alone, without validation doesn't work, and will explode in the hands of newbs. That's why my notion about this is _validate_, log messages, _then minify_, log messages.

But, per your own example, even if minification doesn't interest you in the least, adding a optional, configurable HTML validator that watches for saves on html files (and logs errors) might actually save you some headaches. Hipsters who don't care about validation can safely ignore it at their peril.

**Comment by YohannParis** [comment]
> Finally, minifying HTML doesn't really save that much space. It's far better to reduce the number of HTTP requests than it is to trim a few kilobytes off of an HTML file.

I completely agree on this, but know Google start to be picky about it:
https://developers.google.com/speed/docs/insights/MinifyResources
https://developers.google.com/speed/pagespeed/insights/

Could it be useful to not minimize HTML but just automatically remove all the white spaces?

**Comment by devilskitchen** [comment]
My assumption is always that CodeKit is right, and I must have ballsed up my code.
