### ISSUE TITLE
About Assets usability

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#33]
I played around a little bit with the assets. It general works - pretty pretty nice. But i have one or two nagging points that came up along the way, nothing grave, but they did at least make me think from once or twice 

1) I guess a point "install 'jquery' " in the context menu inside the "installed" pane is unnecessary. 

![install install](https://f.cloud.github.com/assets/1665422/1776836/09c3af4c-681c-11e3-9e24-44163a8cc3d6.png)

2) The icons are a bit unintuitive. Took me a while till i figured out that the stars mean favorite, especially since there are grey (filled) and yellow stars with not much of a difference between the yellow and grey colors. There isn't also a visual feedback (that onclick something happens) like a favorites count in the pane header (e.g. Favorites (9) ). Same with Installed (e.g. Installed (2) )  

3) The three panes are more or less identical information wise (what is displayed within their columns in each pane). i am still thinking what might be the best approach but to start a discussion i might throw in a few suggestions: 

**Components**
- The informations are good like name, stars, forks and description
- The checkmark icon doesn't set itself apart from the cloud icon much. 

**Favorites**
- I think the stars and forks columns aren't necessary within favorites. Maybe a Codekit internal statistic column like "installed in x projects" might be more of interest. 

**Installed**
- I think the stars and forks columns aren't necessary within installed. 
- The stars column might carry installed version and forks the latest version. Description could carry the normal description string again. 

In general i dislike the context menu with "install" and "go to the repository". The direct repository link might be  merged with the component name - make the component clickable. Means if you click on the name you get directly to the repository in the default browser. 

And maybe change the install button behaviour. Take the cloud icon or a button for install a component and then in contrast use a uninstall or remove button instead of a check mark to remove a component from a project again. The user would be in total control. As a positive side effect the context menu would be gone. 

Just a few thoughts. Best regards Ralf

**Comment by sebastiannm** [comment]
I can also add that it would be better if the sort of every column is different.
On favorites it would better if it is after name, and on components after stars. It would be easier to find things this way

**Comment by mdavis1982** [comment]
@rpkoller Thanks for the detailed information. These are my thoughts on your suggestions (note, I'm not affiliated with CodeKit in any way at all - I'm just a beta tester the same as you)

1) :+1: I agree that the "Install jQuery" isn't necessary in the "Installed" pane. @bdkjones 

2) I both agree and disagree about the icons. I think the stars are fine - it's becoming a common UI concept (see Spotify for the same concept - and many other apps). I agree, though, that counters in the titles of the panes may be nice. @bdkjones 

3) I'm not sure I agree with the change in the columns:

**Components**
- I actually think this is fine as is

**Favorites**
- The stars are definitely necessary - it makes it easier to "un-favorite" an item.
- The forks column probably isn't necessary. 
- An "installed in x projects" column wouldn't make much sense as CodeKit could really only tell you about projects it currently has added to the app - so the number wouldn't be consistently accurate.

**Installed**
- The stars are necessary - it makes it easier to "un-favorite" an item.

I think the expected behaviour for me would be to double-click the component title to install it - not go to the repository. @bdkjones Would that be possible? I'd also expect that you could right-click to go to the repository, or have another column with an arrow in it pointing to the right to go to the repository.

Just my 2 cents :smile:

**Comment by rpkoller** [comment]
@sebastiannm i would second that. But i guess the main issue is that Codekit isn't remembering the the default column after which the list should be sorted. Forgets it after a restart. I will file a separate issue. 

@mdavis1982 
about  2) i don't have anything against the stars. i just wanted to point out that the visual representation is too  reduce by those light colors and the similar coloring of light yellow and a darkish grey both filled opaque (hope that's the right word ;) ) - they just don't pull that much attention. 

about favorites) 
with stars i refer to the column "stars" showing the count of github stars not the actual star "object" ;)))) 
sure it would be only of a statistical value for yourself in respect of in how many projects you already had used one particular plugin over the months and years. 

about installed) 
same like favorites ;) i referred to the github stars ;)

**Comment by bdkjones** [comment]
Yea, I'm not exactly content with how this area works. 

The trouble is that Bower is constantly changing and they're talking about a massive rewrite to make the thing not actually suck at life -- as in, they will be able to remove old, outdated components. So I'm wary of putting too much into Bower at this point. 

In fact, I'm considering just rewriting the basics of it in C and ditching Bower altogether. So, I'm going to delay this for 2.1 right now.
