### ISSUE TITLE
Live Refresh does not work if certain optional html tags are omitted

### ISSUE THREAD

**Issue by receter** [bdkjones/CodeKit2#341]
Live Refresh did not work for me. It took me some hours to find the Problem, here is what I have observed:

For this HTML refreshing works:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document1</title>
</head>
<body>
</body>
</html>
```

Once I remove </head> (which is a optional html tag) live refresh stops working after saving 2 changes, so first save gets recognized but second and so on will have no effect.

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document124r54</title>

<body>
</body>
</html>
```

If I add the </head> tag and remove "?ckcachecontrol=1399384770" from the url it works again.

**Comment by bdkjones** [comment]
Invalid. The closing `</head>` tag cannot be omitted in your example because the `<head>` element is immediately followed by a newline character, which is considered a "space character". 

As per the HTML5 spec, 8.1.2.4:

```
A head element's end tag may be omitted if the head element is not immediately followed by a space character or a comment.
```

Here are my formal thoughts on the matter:

In more general terms, omitting the closing tags for major sections such as head, body, and html is bad practice on the scale of the Titanic’s navigational plan. The only reason this nonsense even made it into the spec is probably because some stupid hipster who’s spent too much time writing “modern” whitespace-sensitive, “leave-out-everything-that-could-give-any-context-to-this-code” languages whined until the W3C finally caved just so he would shut up. 

I wish I could slap whoever thought it was a good idea to make this part of the HTML5 spec. It’s mind-boggingly dumb. 

CodeKit looks for the “</head>” tag so that it can place its reload javascript tags just before it. If you page has no closing head tag, the app won’t add these special javascript tags and therefore, refresh won’t work.

**Comment by receter** [comment]
haha, I like your answer! You are right, the second html code is not valid (but still validates in all html5 validators I know). In my original code the starting <head> tag was not there either.

I used Jens Meiert's "World’s Best HTML Template", not the best template when it breaks code kit ;)
http://meiert.com/en/blog/20080429/best-html-template/ http://hell.meiert.org/core/html/template-html5.html

Still, I think that just searching for the first occurrence of "</head>" has some downsides. Beside the problem I faced, it may also break if </head> occurs in a comment in the head. This is the case for some snippets that explain how to integrate them in a comment, like:

```
<!-- Place this code immedeatly before the </head> tag in your code. -->
```

But I can't think of a much better solution yet. You could parse the html code, but this would be much slower for big html files. One other idea would be to search for the first element that is not in the content model of <head>, but this still may require to parse the whole file.

To come to an end, I am totally happy to include the </head> tag. It was painful to find this issue, so it would be great if this information is available somewhere. And keep an eye on html minifiers as they may get the idea to remove optional tags some day.

**Comment by bdkjones** [comment]
Hi Andreas,

```
Thanks for following up. That template looks like it’s 6 years out of date.

The </head> in a comment is an interesting point. I’ll have to add some more checks.
```

-Bryan
