### ISSUE TITLE
Add output file suffix to .less compiled files

### ISSUE THREAD

**Issue by rotx** [bdkjones/CodeKit2#349]
For a minified /source/script.js JavaScript, I can get CodeKit to name it /public/js/script.min.js.

I would like to do something similar for /source/file.less, but currently (CodeKit 2.0.5) it's either the path (/public/css) or the path component (.less -> .min.css), but not both.

I can manually set the output path for each less file, so it's not a showstopper.

**Comment by davidjdixon** [comment]
the .min for JS files isnt part of the JS output path, but an global enforcement on JS files to prevent naming conflicts (it irks me quite a bit, but i understand the reasoning for this to an extent).

I also do understand the simple approach taken current by codekit for the "either/or" output path manipulation, and while I would like a more flexible solution, I would be more concerned that it may cause a few other issues down the line (for support especially). 

My own preference for the output path change would be to allow multiple path component replacements (which would solve your use-case as well), rather than going down the pure suffix route (personally, I wouldn't want to ever suffix css files, as I feel its pointless). But I dont necessarily expect this to come around as its more complexity for **very** little gain.

**Comment by bdkjones** [comment]
Implemented in version 2.1. Thanks!
