### ISSUE TITLE
Server testing on IE10 asking to leave page for all links

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#351]
When using CK server to test websites, i've noticed recently that when using the IP on IE10, bad things happen.

![snipimage- 7b18bcfa92-0d76-47c3-be62-ce41d0c81bfc 7d 3](https://cloud.githubusercontent.com/assets/1001935/3025930/5e2f36a6-e00c-11e3-9cff-bba9b317dcb3.png)

Every link becomes this nasty popup saying "Are you sure you want to leave?!" "NULL".

**Comment by bdkjones** [comment]
Yea. Microsoft has hard-coded IE to always show this alert whenever a piece of Javascript (such as codeKit's refresh script) tries to change the address in the URL bar. Nothing I can do.

**Comment by yratof** [comment]
ha, fantastic. I bet the head of IE security feels awesome.

Cheers Bryan

**Comment by lukasfronc** [comment]
Maybe stupid question, but...

Leaving question pop-up is shown if I manually click on link on the page (IE 10 - Win 8 via Parallels Desktop and IE 11 - Win 7 native) – it means URL change by user, not by JS.

And, If you say this is because JS is changing URL, what about don't use ckcachecontrol (is only reason of change URL by JS, isn't it?) on IEs?

Thank you for react.

**Comment by bdkjones** [comment]
Unfortunately, no. ANY page reload that CodeKit performs has to be done with Javascript. There is no way for CodeKit to simulate a user manually clicking on a link. 

If you find a way around this, I'll implement it. But so far, I haven't been able to find one.
