### ISSUE TITLE
Feature request: Pass path of processed file(s) to hook

### ISSUE THREAD

**Issue by rotx** [bdkjones/CodeKit2#355]
By way of example: I want to run gzip on all my .html output files.
Currently, I have do a search of the file system:
/usr/bin/find public -name "*.html" -type f -ctime -10s -exec /usr/bin/gzip -kf9n {} \;

This will cause gzip to run on anything named html in the public directory that was created in the last 10 seconds (and can thus pick up files that weren't created by CodeKit, or created by CodeKit in a previous run, etc).

If CodeKit were to pass in the path of the processed file(s) as command line argument(s) to the hook, this could be simplified to (for example):
shift
/usr/bin/gzip -kf9n $*

Alternatively, if CodeKit set an environment variable, this could be:
/usr/bin/gzip -kf9n ${OUTPUTPATHPROCESSED}

As an alternative alternative, CodeKit could do a textual search/replace on the hook script before submitting it to bash/AppleScript, for example:
/usr/bin/gzip -kf9n @codekit-processed-path

**Comment by chris-scheurle** [comment]
I'd really love to have that feature, too. :)

**Comment by subhaze** [comment]
I was just looking for this as well, +1 on adding this in.

This could more easily open up the door for things like an ng-annotate hook for angular.js projects, JSX compile hook for react.js projects, gzip (like described above), etc.

My use case was looking into what custom CodeKit Framework was, if any, getting compiled. If it were a specific framework pull in some font/image assets relative to the location of where that file was processed, right now I'm just using a variable at the top of the hook so it's usable x-projects.

I guess my use case could open up the door for possibly allowing a custom framework to have an asset folder that is pulled over into the project, as that's basically what I'm currently trying to solve.

**Comment by rmhall** [comment]
+1 Sorry didn't catch this till now and accidentally opened a duplicate: https://github.com/bdkjones/CodeKit/issues/533  feel free to drop my dupe.

**Comment by bdkjones** [comment]
Implemented for 2.2.1, for Bash Hooks. You can access two environment variables in your Hook:

```
CK_INPUT_PATHS
CK_OUTPUT_PATHS
```

Each is a colon-separated list of full, disk-root-relative paths. `CK_INPUT_PATHS` contains the paths to the files that CodeKit compiled (sass, js, less, etc.) and `CK_OUTPUT_PATHS` contains the paths to the resulting output files. 

Couple key points:
1. These are not guaranteed to exist. Some operations in CodeKit, such as syntax checking, will trigger a run of Hooks, but the variables above will not be set because no files were compiled. You MUST check for the existence of these variables in your Hook; do NOT assume they will be there. 
2. File paths are not escaped. So if a path has a space in it, you'll need to escape that yourself before passing it along. This appears to be the convention for environment variables containing paths on OS X. My recommendation is to always wrap the paths in quotes. 
3. Ancillary files such as source maps won't be included in the variables above. You can infer their paths by looking at the output file's path.
4. The variables may contain a metric-shit-ton of file paths. If a user selects 893 Sass files and hits "compile", there will be 893 file paths in these variables. I recommend performant scripts.
5. It is very possible that the `CK_INPUT_PATHS` variable will contain a path OTHER than the path to the file that actually changed on disk. For example, if `main.scss` imports `sub.scss` and I save `sub.scss`, CodeKit walks the relationship and recompiles `main.scss`. The path to `main.scss` would appear in the variable; not the path to `sub.scss`, even though the latter file is the one that triggered the action.
