### ISSUE TITLE
Request : Permit CORS from Codekit server

### ISSUE THREAD

**Issue by timhatch** [bdkjones/CodeKit2#360]
I have a project which loads JSON data from a 3rd party server. It would be helpful if Codekit's internal server included options to allow CORS requests (e.g. from user identified external servers) - this would allow me to avoid the control-r loop that I otherwise have to use.

**Comment by bdkjones** [comment]
Implemented in version 2.1.

### Details

The internal server now sets the HTTP header `Access-Control-Allow-Origin: *` on all responses. This applies to the internal server ONLY. If you're using an external server, it's up to you to have your server return the appropriate CORS header (CodeKit will forward that header on to the browser as the proxy response is handled). 

Note that because the internal server now allows all origins, you can't set CORS cookies or provide CORS credentials in your request headers --- I think that should fail gracefully, but I haven't tested it. 

And, of course, this obviously has security implications. Because the CodeKit preview server is not used on the Internet, it's okay to expose it to cross-site-scripting. But if you forward port 5757 outside of your LAN or if you have people on your network who would like to screw with you, this is now a vulnerability.

### Rationale

I debated offering the ability to list specific domains that should be authorized for each project. But doing so would slow down the internal server, as it would need to check that list for EVERY HTTP response and then formulate the appropriate header, etc. 

The approach above allows your projects to issue CORS requests. If you need more fine-grained control over the environment (example: testing authentication credentials for specific domains, etc) then it's time to set up an external server, configure it how you'd like it and have CodeKit act as a proxy.
