### ISSUE TITLE
Re-minified js

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#370]
Already minified files should be ignored.

Once I open jquery.min.js (which is already minified) and hit cmd+s, Codekit compiles it to jquery.min.min.js.

**Comment by drgullin** [comment]
I've tried to remove config.codekit and a project from the Codekit, then, I set `*.min.js` in Skipped items & paths and re-added the project. Nothing changed.

**Comment by bdkjones** [comment]
Well, there's no way for CodeKit to determine if a file is "already minified". Relying on the presence of ".min" in the filename is not effective. Some folks use different identifiers such as "-min", "minified", "-prod", etc. Trying to guess whether a file is already minified based on the filename is a losing game.

CodeKit will automatically disable output for files that are at the output location of a different file. So, if your output paths are set correctly in your Project Settings, so that the JS file that creates the .min file has its output path set to the location of the .min file, the .min file will be auto-ignored.

**Comment by einkoro** [comment]
@bdkjones Is that supposed work with "to the same folder as the source file" option in output paths as well or only when using specific folders?

**Comment by bdkjones** [comment]
Should work in all cases.
