### ISSUE TITLE
Notification details

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#371]
Codekit moves its window on top of the other apps when there's some error in compiled file (and shows me the actual error).

That's not nice, since:
1) maybe I know, where the issue is (no need to inform, you take me away for a nothing)
2) I've to switch back to my editor from the Codekit's window every time (since it goes on top), on each error.
3) When I check where the issue is (on which line), I've to switch back to my editor, to make edits. No short hotkey for this, hello mouse or cmd+tab.
4) I've a built-in errors checker directly in my editor. So you take me away from it again, for a nothing.
5) Maybe, an error occurred not because of me, but because of the autosave action in my editor.

I sugges:
1) When there's an error in some compiled file, show me please an excerpt of this error directly in notification.
2) Please don't show me an editor until I click the notification (don't move a focus from my editor to a different app).
3) Make an option to setup a delay for a notifications.
4) Add a close button to notifications.

Thanks.

**Comment by jackw** [comment]
Hey,
I'm not sure if I'm understanding fully but have you checked Codekit's preferences? It has options for disabling 'bringing codekit to the front'...

![codekit-settings](https://cloud.githubusercontent.com/assets/73201/3285024/1749b9e0-f534-11e3-9c15-a2ff50ed37ae.jpg)

I think this will solve most of your issues!

**Comment by bdkjones** [comment]
I'd love to show errors in notifications. The problem is that each compiler does things different and I can't parse the actual error information (line number, bad text, reason) out of the result the compilers spit out because they spit it out as a blob of text. I've opened requests with each of them to return results as some sort of parsable output, such as JSON. So far, that hasn't happened. When it does, I'd love to implement better error notifications.

In the meantime, the preferences options will keep CodeKit in the background.
