### ISSUE TITLE
Launch editor from CodeKit

### ISSUE THREAD

**Issue by heathflohre** [bdkjones/CodeKit2#384]
An option for or button by the file for launching the preferred editor. Right now, if you double-click the file, it shows it in the Finder.

**Comment by DrieStone** [comment]
I kind of can't believe that CodeKit doesn't already do this. I'm super annoying that I keep double clicking files to edit and it opens new Finder windows instead. Why can't I just set a default editor and use CodeKit to open my files in Sublime/BBEdit/Etc? 

Honestly, this was the expected behavior and I spent the last 30 minutes looking through help and watching videos before I realized it doesn't have the capability to actually do this. 

The lack of this feature took this from the next best thing for working on the (literally) dozens of websites I manage, to "oh well, this might be handy, but I'm not going to waste my time moving everything into CodeKit".

**Comment by scottybe** [comment]
Is this still the case? I also spent time trying to figure out how to get CodeKit to open up files in the default editor instead of showing the file in the Finder...

**Comment by bdkjones** [comment]
<img width="641" alt="screen shot 2016-04-29 at 11 19 01" src="https://cloud.githubusercontent.com/assets/926566/14925425/3da7851c-0dfc-11e6-95e7-5f3e3558ce29.png">

**Comment by bdkjones** [comment]
Yea, I remember this issue. You'd be blown away by how many angry, ranting emails I get that:
1. Go something like: "WHY DON'T YOU SUPPORT X HOW ARE YOU THIS STUPID I AM SO ANGRY WHY DON'T YOU GO JUMP IN FRONT OF A BUS."
2. Can be replied to with a single screenshot of some preference.

**Comment by scottybe** [comment]
Thank you! (and please don't jump in front of a bus)
