### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by chrfickinger** [bdkjones/CodeKit2#385]
Transparent Project icons don’t work like they should.
Check attached screenshot to reproduce the behavior.

![screenshot](https://cloud.githubusercontent.com/assets/91317/3479405/611b5d28-0351-11e4-86c9-b7a829765ba4.jpg)

**Comment by bdkjones** [comment]
Actually, it's drawing exactly as it should. If you drag the window around while that popover is open, you'll see that the background behind the icon is 100% transparent, revealing whatever is underneath. 

However, I see how this can look like a bug because you end up with extra things behind your icon. Therefore, in 2.1 transparent icons will now always draw with a white background.

Fixed in 2.1
