### ISSUE TITLE
Autoprefixer not working after 2.1 update

### ISSUE THREAD

**Issue by juergengenser** [bdkjones/CodeKit2#402]
With the latest update Autoprefixer doesn't seem to work anymore. I'm trying to use it within a LESS project...

Thanks in advance.

Regards,
Jürgen

**Comment by bdkjones** [comment]
Hi Jürgen,

Tested over here, it's working fine. Please send me a screenshot of your file settings for the Less file inside of CodeKit. 

Please post the file that's not working along with the CSS output you're seeing after Autoprefixer runs AND what the CSS output _should_ be. Keep in mind that many things like border-radius are no longer prefixed because browsers all support the standard now.

Vague, general bug reports like this aren't very helpful; I need concrete details and steps to reproduce and examples.
