### ISSUE TITLE
Preferences toolbar not using Yosemite theming (Trivial UI)

### ISSUE THREAD

**Issue by davidjdixon** [bdkjones/CodeKit2#413]
If you look at the Codekit preferences toolbar and compare it to (for example) the presences bar of the Contacts app, you should notice a couple of trivial UI issues.

1)  when in foreground, the selected toolbar icon's text label is too heavy
2) all toolbar labels are wrong color (grey instead of black)
3) selection backgrounds do no show rounded top borders
4) if looks like there is a background "above" the standard rounded background (you can see the standard bg coming slightly out of the edges, looking like there is some kind of border. This makes the bg darker, and also contributes to (3)

On preferences in general:

5)  the standard (from Apple) appears to be that form labels are not bold (whereas codekit shows them as bold).
6) The checkboxes used in the general tab are much smaller than the standard sizes used in apples' own apps (main concerns here is accessibility for small screens... on 24 HiDPI screens it looks fine, on 15" macbook screen, its a little straining on the eyes)... applies to 'information' text on compilers tab as well.

**Comment by bdkjones** [comment]
Just looked at this on DP8 and everything appears correct. It looks like this was an Apple issue that got fixed somewhere along the line.

As for bold labels: mine look better than Apple's. 

Checkbox sizes: They are indeed using the smaller of the official sizes because the preferences window's height must remain small enough to fit on the 11" MacBook Air screen.
