### ISSUE TITLE
Inconsistent jshint reporting with "ignore issues"

### ISSUE THREAD

**Issue by otheroom** [bdkjones/CodeKit2#420]
Steps to reproduce:
1. Create main.js, error1.js, error2.js

``` javascript
// @codekit-prepend "error1.js"
// @codekit-prepend "error2.js"
```

``` javascript
if (document.length == 0) { /* error1.js */ }
```

``` javascript
if (document.length == 0) { /* error2.js */ }
```

When main.js is processed there will be an issue reported for each of the error js files:
Expected '===' and instead saw '=='. — column 23

If you then go to the Linked Files panel for main.js and uncheck the Ignore Issues icon for either of the error js files, subsequent builds will not report the issue in the error js file who's syntax should still be checked.

If you edit any of the js files to trigger processing, the proper issue reporting occurs.

Once the issue reporting stops and you don't edit any files, you can change the Ignore settings as much as you like and you will not have anything reported.

CK 3.1.2 / MacOS 10.9.4

**Comment by bdkjones** [comment]
> subsequent builds will not report the issue in the error js file who's syntax should still be checked.

Do you mean when you click the Process button in the CodeKit UI? Clicking Process bypasses the syntax-checking because there's a separate button in the UI to syntax-check the file. 

By contrast, when you _save_ the file in an editor, both the syntax check and processing steps occur (depending on the settings for the file in question, of course).

**Comment by otheroom** [comment]
I didn't realize that the Process button didn't syntax check. With that in mind, it does seem to be working as expected.

Is there a reason that the Process button bypasses the syntax checking?

**Comment by bdkjones** [comment]
Yea. The original reason for the distinction is when you have a JS file with a bunch of semantic issues that you really don't care about. You turn off syntax checking in the options for that file so that when you save it, you don't constantly see a bunch of warnings. 

Then, you could come to the app and click the Check Syntax button to see those issues manually.
