### ISSUE TITLE
[Bug] Import dropping files

### ISSUE THREAD

**Issue by bcmcq** [bdkjones/CodeKit2#430]
I have one javascript file importing all others and then outputting to one compressed js.

Files are being removed from the import list on there own. It's usually the file that I'm working on along w/ a few others. I was thinking maybe I had too many imports but in that case I would imagine that the end of the list would be dropped and not specific files in the middle of the list.
- CodeKit 2.1.3 (17682)
- Mavericks - 10.9.4
- Always w/ .js files
- Multiple projects
- PHP based projects
- Has been happening since the very first version of CodeKit 2

**Comment by goroboto** [comment]
+1!!!!
This drives me crazy - I need to keep screenshots of the compile list (~25 js files) so that I can add the missing files back in when I start having issues.
10.9.4 / 2.1.3 (17682) / Chrome / JS files

**Comment by bdkjones** [comment]
I'm looking into this issue on my end. So far, I haven't been able to reproduce it. 

In the meantime, use the in-file statements instead of drag-drop to create the links between files. See http://incident57.com/codekit/help.html#javascript

**Comment by bdkjones** [comment]
This was fixed in version 2.1.6. 

However, I also introduced a bug that made it impossible to drag files into a CoffeeScript file. (Dragging into the JS file is not affected). I'll be fixing THAT bug in 2.1.7, which I plan to have out in the next day or two. 

But the original "forgetting drag/drop links" issue was fixed in 2.1.6.
