### ISSUE TITLE
The Assets column heads might use triangles to visualize the sort order  

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#46]
At the moment you don't have any visual feedback aside the sorted list itself if the sorting is ascending or descending. i normally like a triangle in the column head of the particular column responsible for the sort order. At the moment there are only names without even any column separators.

**Comment by mdavis1982** [comment]
:+1: I think this would be a good addition

**Comment by bdkjones** [comment]
I've decided to close feature request issues on the beta repo. The reason is that I _have_ to get this app shipped and that means locking the feature set so I can concentrate on killing bugs. 

Once the app goes public, I'll take feature requests again and start implementing them for the 2.x releases.
