### ISSUE TITLE
Feature Request: Granular control on what notifications get displayed

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#472]
I'm not really familiar with Apple's notification API but was wondering if it's possible for CodeKit to have a UI for enabling/disabling what sends notifications to the OS.

This curiosity is spawned from the auto-pausing in the Sublime Text plugin spamming the notifications with 'File-Watching is Paused/Enabled'

https://github.com/subhaze/sublime_codekit/issues/4

My current solution is for users to either disable that feature in the plugin or disable CodeKit notifications at the OS level, the later sadly removes all notifications, which isn't ideal since they can be very helpful.

**Comment by bdkjones** [comment]
It's not possible with Apple's NSUserNotificationCenter API. That's an all-notifications-or-no-notifications thing. 

However, users with Growl installed can select which notifications to display. I'll break these pause/unpause notes into a separate category for Growl.

**Comment by katerlouis** [comment]
I'm confused: 
Okay, Apple's API doesn't give the user much control. But why can't you on App-level? 
I imagine a checkbox alá `Notification on successful compile`.
Checked off then CodeKit simply doesn't fire.

There's probably a reason, but I'm eager to know it.
It's a huge bummer to disable all just because I hit `CMD+S` so damn freakin often.
