### ISSUE TITLE
Make codekit compile output sass files when an imported partial is saved

### ISSUE THREAD

**Issue by jrdn91** [bdkjones/CodeKit2#477]
Is there any way I can get say a file named `style.scss` that imports `_partial.scss` to compile and I make a change to `_partial.scss`? I thought this was a default behavior of sass?

**Comment by bdkjones** [comment]
It is default behavior. Are you sure your import path is correct? Post a download link to an example that shows the issue so I can see it on my end. (And read the readme at the front of the repo.)

**Comment by bdkjones** [comment]
I need an example that shows the issue; as far as I'm aware the dependency-linking is working great in CodeKit 2.1.8. Thanks.

**Comment by jrdn91** [comment]
It seems to work okay with one level of dependencies. But if I import a partial called `components/_all.scss` that imports partials next to it like `@import '*'` the third level deep dependencies that get saved do not cause the main file to compile. But saving the `components/_all.scss` file does. So if I remove the `_all.scss` file and just import all the partials in a directory in the main output file, I can save any files in that directory and it causes the main output file to compile just fine. For the time being I think this is okay but I can see where nested imports in a more complex structure might get hectic to manage this way. If I come to this crossroad again I will create an issue in the way outlined in the readme. I'm just putting this here to explain where I'm at the the workaround I have found.

**Comment by bdkjones** [comment]
Yea, the issue here is that "globbing" sibling files is not supported. You can write `@import 'somefolder/*'` to glob all the files in a subfolder, but you can't use globbing for siblings --- CodeKit won't notice those import links.

The primary reason for this is that it would be stupid-easy to accidentally create infinite import loops. 

Adjust your structure so that your main output file imports all the child files in your `components` folder either with a globbed link or individually and that will solve the problem. There is no limit to the number of levels CodeKit charts dependencies; it will work for a chain that's two files long or 54 files long.

**Comment by jrdn91** [comment]
Gotcha, thanks!

**Comment by ehausen** [comment]
I definitely think this is a flaw! There are many themes that nest imports to keep things tidy. I expected Codekit to follow standards and now I have to resort to trickery and modifying existing frameworks. (Zurb Foundation Drupal Theme)

**Comment by ehausen** [comment]
At the very least the software should give a warning that is not behaving as expected by spec.

**Comment by bdkjones** [comment]
No. Import gloving was specifically _rejected_ by the Sass team. It is in no way part of "the spec". It is an addition used by some folks and should be treated with extreme caution. Globbing sibling files is incredibly dumb because the globbing syntax literally means, "import all files in this folder", which would include the file containing the import statement. Framework authors who are doing this need to stop writing poorly-structured code and fix their libraries. The appropriate action is to file bugs against those frameworks and have their structures adjusted.

**Comment by ehausen** [comment]
I stand corrected. :)
