### ISSUE TITLE
Feature Request: Grouping in Projects Sidebar

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#498]
It would be great to be able to create folders in the Projects Sidebar.

**Comment by bdkjones** [comment]
Yea, this request comes up every now and then.

It is not a good idea to keep tons of projects in the app. That uses WAY more resources than you want because CodeKit watches everything in the project folders (even inactive/disabled projects).

The right approach is to keep just the few projects you're actively working on in the app and remove older projects completely. All settings are saved in project config files, so they'll come back just as you left them the next time you add the project folder to CodeKit.
