### ISSUE TITLE
Codekit Lost All the Projects

### ISSUE THREAD

**Issue by JonnaIsaac01** [bdkjones/CodeKit2#547]
Hi,

Codekit has lost all the projects I was working on (there were only 2). This is the second time this has happened, and I'm positive I was not holding down the shift key. I also recently ran the disk repair utility and I installed Codekit only a few months ago.

Was there a resolution to this besides re-installing Codekit?

Thanks!

**Comment by bdkjones** [comment]
Do you have the Sublime CodeKit plugin installed?

**Comment by JonnaIsaac01** [comment]
Hi,

Yes, I do!

**Comment by bdkjones** [comment]
That's the issue. The plugin quits and launches CodeKit when sublime loses focus. If you use a keyboard shortcut to close the sublime window, the shift key is down when the plugin talks to CodeKit. Turn that feature off in the plugin.

**Comment by JonnaIsaac01** [comment]
I don't use a shortcut to close the Sublime window.

**Comment by subhaze** [comment]
Oh wow... I've not had this happen but can definitely see the potential of this happening...

The quitting CodeKit is off by default but I've added a notice on the readme since it will auto start CodeKit by default.

I'll see if there's a way to detect key presses in the ST API to try and guard or a minimum warn the user if the shift was pressed when the call to open CodeKit was made.
