### ISSUE TITLE
CK Server messing with PHP superglobals

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#60]
A legacy project of mine uses PHP's  `$_SERVER['HTTP_HOST']` to decide what db config to use. The project wouldn't connect to the DB so I did a little debugging...

``` php
// Notice the mismatch between the length and the string
var_dump($_SERVER['HTTP_HOST']);
// string(9) "imarc.local:5757"

var_dump(substr($_SERVER['HTTP_HOST'], 0, 9));
// string(9) "imarc.local:5757"

var_dump(substr($_SERVER['HTTP_HOST'], 0, 8));
// string(8) "localhos"

var_dump($_SERVER['HTTP_HOST'] === "imarc.local:5757");
// bool(false)

var_dump($_SERVER['HTTP_HOST'] === "localhost");
// bool(true)
```

So, it outputs the CK server URL but what's hidden behind – and used in string comparison – is `localhost`.

I use MAMP PRO on port 80 with an external server address similar to `http://localhost/my-old-project.com` in my project config.

**Comment by bdkjones** [comment]
I'm afraid I don't understand. What's the expected outcome here?

**Comment by marcaube** [comment]
Ok, that wasn't clear.

The expected outcome is that `imarc.local:5757` should be 16 characters long, not 9 and shouldn't change to `localhost` when doing a substring on it or using it in a comparison.

It should be one string or the other, not both.

I don't quite understand what's happening myself, the HTTP_HOST string from CK2 turns to `localhost` once compared or manipulated. I figured it has to do with how CK2 is dispatching request to php files to an external server behind the scenes.

I'll have to try it with different versions of PHP tomorrow and see if I also get the same results in modern frameworks that wrap the $_SERVER super global in a PHP object.

**Comment by hlissner** [comment]
I'll test this once I get home, but I'm going to fancy a guess that the CK server scans the output of your external server in order to inject the JS script links. Along with that, I figure it clumsily replaces all occurrences of "localhost" with your hostname (to correct links).

Try this:

> echo 'localhost';

and see what you get from that.

It doesn't solve your DB connection issue, but it'd explain the hostname switch.

**Comment by marcaube** [comment]
Yup, you nailed it, `<?php echo 'localhost';` outputs `imarc.local:5757`.

**Comment by hlissner** [comment]
Good to know. Also, as an fyi: for setups using external servers on other ports, CK will look for hostname + port number (e.g. "localhost:8888") to replace with "hostname.local:5757".

Anyhow, I think it's safe to close this issue.

**Comment by peterhartree** [comment]
I think this behaviour should be prominently flagged when CK2 is released. I lost quite a bit of time yesterday trying to figure out why the following never matched:

```
  if($_SERVER['HTTP_HOST'] == "phweb.local:5757"):    
    $cdn = '';
  else:
    $cdn = 'http://xyz.cloudfront.net';
  endif;
```

Of course, I needed to check for my external server's hostname. But, it took some head scratching to figure this out because:

```
echo $_SERVER['HTTP_HOST'];
// outputs phweb.local:5757
```

**Comment by bdkjones** [comment]
Yea, the issue here is that when you configure CodeKit to use an External Server, CodeKit becomes a proxy server. The browser is going to throw the HTTP request to CodeKit using the host header `[computername].local:5757`. 

When CodeKit then forwards that request to your External Server, it's going to modify that HOST header to be the external address of your server. This is really critical. Without this modification, platforms like Wordpress enter into an infinite redirect loop. 

I'm not sure why PHP is setting the HTTP_HOST value to the original address. CodeKit's internal server definitely modifies the `HOST` HTTP header before forwarding the request over to the external server, which is where PHP is running. I'm not a PHP expert, but if someone can tell me why it's behaving this way, I may be able to combat it.

**Comment by peterhartree** [comment]
I'm not an expert on PHP's internals, but I know it is possible to manually redefine the HTTP_HOST value with a line like the following:

```
<?php
    $_SERVER['HTTP_HOST'] = 'myexternalserver.dev';
?>
```

I don't know how things are working behind the scenes with CK2 but one potential avenue to explore might be to use .htaccess to invoke php's auto_prepend_file function to load a file containing something like the above.
