### ISSUE TITLE
Update libsass doc

### ISSUE THREAD

**Issue by bakura10** [bdkjones/CodeKit2#7]
In SASS config, it says that lib sass does not support placeholders and Compass. However it successfully compiles my files which uses SASS placeholders and Compass project. Does CodeKit does not follow the "use libsass" if it detects there is a Compass project?

**Comment by bdkjones** [comment]
Be careful. "Successfully compiles" does not mean "Generates correct CSS". Go check the CSS by hand and I bet you'll find that it's not valid. There are active issues about this over on the libsass repo.

As for your question: yes, the libsass setting is ignored completely in Compass projects. Those always compile with the Compass Ruby gem.

For now, I'm going to close this issue because the warnings under libsass are, as far as I know, valid. I'm in touch with the libsass team on a regular basis and I'll update the warnings when they no longer apply.
