### ISSUE TITLE
The Metaphorical Fridge is Not Working

### ISSUE THREAD

**Issue by BabylonSix** [bdkjones/CodeKit2#73]
I don't know how to file this as, so here goes…

iPhone and iPad resolved the von.local:5757 and showed the site just fine,

my Nintendo Wii U and Nintendo 3DS browsers didn't, kept giving me error messages.

What finally fixed it for me was when I tried the following.
von.local:5757 => 192.168.1.75:5757

Add it to the documentation maybe?

But with this fix, the site doesn't auto-refresh on save and has to be 
manually refreshed on those devices that need it.

**Comment by ghost** [comment]
Sounds like this issue I posted about for Android devices. This has to do with how the device handles name resolution. We came to the conclusion that this wasn't a Codekit issue but rather that the devices just can't handle translating the name.

https://github.com/bdkjones/codekit2beta/issues/38

**Comment by BabylonSix** [comment]
I see, I bet it would save people time if this is mentioned in the documentation somewhere.

**Comment by bdkjones** [comment]
The issue is that these devices don't support Bonjour networking. Beta 4 resolves the issue by:

1) Defaulting to non-bonjour IP addresses if the Mac is connected to a network for the injection scripts.

2) If the Mac is not connected to a network, falling back to the Bonjour networking.

3) Automatically restarting the server when the network connection changes.
