### ISSUE TITLE
Compiling broken when Output style none is selected.

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#8]
Codekit stucks on compiling JS when Output style: None is selected.

**Comment by bdkjones** [comment]
Ha. The compile button shouldn't even be available if 'none' is selected. You'll need to restart the app. Good catch.

**Comment by rasmusbe** [comment]
Should it even be a none option? Isn't that the same as unchecking the output file checkbox?

**Comment by rasmusbe** [comment]
Also stucks if you select multiple js-files and compile them and one of these has none as output style.

**Comment by bdkjones** [comment]
So I added the 'none' option about 9 months ago in response to a bunch of confusion people were having with CodeKit 1. But after further review, I've decided to yank it back out and just do some more work on my end to determine the user's intent in a given situation.

This issue is fixed in the next release by nuking the 'none' output style option.
