### ISSUE TITLE
Of IE and Autoreloading

### ISSUE THREAD

**Issue by hlissner** [bdkjones/CodeKit2#89]
Time for a little sit down with everybody's _favorite_ browser!
# IE 10 & 11

Auto-reload "works", but asks for confirmation each time the specified page is modified: 
![screenshot dec 22 19 09 56](https://f.cloud.github.com/assets/510883/1798702/911c850c-6b66-11e3-8044-9562f4a5ed68.png)

Clicking "leave this page" will invoke the reload as normal. Clicking "stay" will throw 

> SCRIPT16389: Unspecified error. 
> lpckrp.js, line 1 character 2697

in console, then the connection will timeout and kill auto-reload.

_However_, neither IE 10 nor 11 produces this dialog when only stylesheets or scripts are refreshed—only when the page is changed. Stylesheets/scripts auto-reloading work fine.
# IE 6 & 8

Auto-reload doesn't work at all. Both browsers choke on lpckrp.js with the error message: "object expected".

![screenshot dec 22 19 18 32](https://f.cloud.github.com/assets/510883/1798720/c3393a0c-6b67-11e3-8567-c7444183bde3.png)

![screenshot dec 22 19 10 29](https://f.cloud.github.com/assets/510883/1798703/a501f890-6b66-11e3-938d-1c674068b0c9.png)

---

Both were run in the http://modern.ie Win7 and WinXP VMs. Frankly, IE <10 doesn't seem high priority at all, but that dialogue on 10 and 11 is a bit of a drag.

**Comment by bdkjones** [comment]
I'm not sure if there's anything I can do about the former issue. I think that dialog pops up each time a page tries to go to a url without user action.

As for IE 8 and 9: screw that. I have no time to deal with that level of incompetence.

**Comment by smlombardi** [comment]
Curious, do ANY re-loaders work with IE? I bet not.

**Comment by hlissner** [comment]
> As for IE 8 and 9: screw that.

Hah, I hear ya. As for the dialog, I've done the opposite before (overriding the window's onbeforeunload handler to make it ask for confirmation), so I tried cancelling it, but no dice :(. Guess there's no helping it.

**Comment by mdavis1982** [comment]
@bdkjones I'm assuming this is one of those things that people will need to live with. If so, can we close this issue?

**Comment by bdkjones** [comment]
Yea. I'm not too worried about IE < 10 and I'm certainly not going to waste a single second of my time dealing with IE6. Everyone that still uses IE6 should be rounded up and shot into the sun.

**Comment by bdkjones** [comment]
For what it's worth, I spent some time googling "disable are you sure you want to leave this page prompt in IE" and found some threads where folks were having the same problem.

No one had an answer for how to disable this. It's just a part of IE, I guess.

**Comment by bdkjones** [comment]
More research: It looks like IE may be implementing a custom `.onBeforeUnload()` handler to show this dialog window. It _may_ be possible for me to kill that by hacking the unload handler to stop the default action. However, that would also kill any scripts that the developer has assigned to run on the unload event, so that's not a good solution.

The answer appears to be: you'll have to suffer through this dialog when testing in IE until Microsoft updates the browser and gets rid of it.

**Comment by bdkjones** [comment]
It's such a shame that stuff like this still plagues IE. They've come such a long way.

**Comment by davidjdixon** [comment]
Sorry to comment on this old thread but this issue still plagues IE11, and it appears to be due to due to a a null return on the onbeforeunload() method (see http://stackoverflow.com/questions/16528365/why-is-jquery-beforeunload-showing-a-message-even-when-returning-null-in-interne). Removing the return of 'null' should solve this bug bear.
