### ISSUE TITLE
Feature Request: Process .kit includes before including

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#97]
Something for the 2.1 release perhaps, but it would be nice if there were an option for the `.kit` processor to run other processors on included files before including them. Use cases include:
- process `.LESS` or `.SCSS` files to generate pure (or just compressed) CSS before including them within `<style>` tags.
- convert markdown to HTML markup and then including it.
- combine prepended/appended JavaScript files before including them within `<script>` tags.

**Comment by bdkjones** [comment]
You should include the _output_ file that's generated when a Less or Scss file is compiled. In CodeKit 2, the app will link these files to your Kit file and when they are changed, the Kit file will automatically recompile.

**Comment by sathomas** [comment]
Although this is really a feature request, based on @bdkjones comment, there may be a bug, so I'm going to reopen. (I won't be offended if it's closed again right away). For my project I want to inline a few critical styles (those that apply "above the fold". I have a SASS file for those styles, and I've got CK set to create the resulting (compressed, naturally) CSS file in an intermediate folder. Then I include the contents of that intermediate CSS file in my `index.kit` file (encapsulated within `<style>` tags, of course).

If I save the SASS file, CK correctly builds the CSS file, and it correctly builds the `index.html` file (from `index.kit`). However, sometimes (not consistently, alas) the resulting `index.html` file has styles from the prior version of the intermediate CSS file. Seems like there may be some kind of race condition going on where CK is triggering the `.kit` compile **before** the SASS compile has finished. (I'm guessing this is somehow related to disk cacheing in OS X, but I'm way out of my league there.)

**Comment by sathomas** [comment]
BTW, this wasn't really a problem until Beta 5. But now that the double compile bug is fixed, it crops up quite a lot. So much so that it's getting pretty much a habit for me to save all files twice. Kind of a pain.

**Comment by bdkjones** [comment]
This should be fixed in Beta 11. In the meantime, make sure you've got quotes around the filenames in your `@include` or `@import` statements in your Kit files. 

As for the general feature request: I am pretty opposed to mashing together all the different languages. Including the Sass, Less or Stylus file directly into a Kit file opens the door to all sorts of complex problems. It's the same as folks wanting to combine Less and Sass into a single file --- "Just have CodeKit compile the parts of the file differently and then throw it altogether!" Unfortunately, that becomes nearly unmaintainable.
